import { useState, useEffect } from 'react'

// Module-level cache so navigating between legends doesn't refetch.
let cachedPromise = null

function fetchLegendCards() {
  if (!cachedPromise) {
    cachedPromise = fetch(`/legend-cards.json?d=${new Date().toISOString().slice(0, 10)}`)
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`)
        return res.json()
      })
      .catch((err) => {
        // Reset so a later visit can retry.
        cachedPromise = null
        throw err
      })
  }
  return cachedPromise
}

export default function useLegendCards() {
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    let active = true
    setLoading(true)
    setError(null)
    fetchLegendCards()
      .then((json) => {
        if (active) setData(json)
      })
      .catch((err) => {
        if (active) {
          setError(
            err.message?.includes('404') || err.message?.includes('HTTP 4')
              ? 'Card analysis is not available yet. It is generated by the daily data update.'
              : `Failed to load card analysis: ${err.message}`
          )
        }
      })
      .finally(() => {
        if (active) setLoading(false)
      })
    return () => {
      active = false
    }
  }, [])

  return { data, loading, error }
}
