import { useMemo } from 'react'
import useLegendCards from '../hooks/useLegendCards'
import './LegendAnalysis.css'

const BASE = 'https://riftdecks.com'

// Preferred display order for card-type sections.
const TYPE_ORDER = ['champion', 'unit', 'gear', 'spell', 'battlefields', 'runes', 'sideboard', 'other']
const TYPE_LABELS = {
  champion: 'Champion',
  unit: 'Units',
  gear: 'Gear',
  spell: 'Spells',
  battlefields: 'Battlefields',
  runes: 'Runes',
  sideboard: 'Sidedeck',
  other: 'Other',
}

const fmtPct = (v) => `${Math.round(v * 100)}%`
const fmtMoney = (v) => (v == null ? '—' : `$${v.toFixed(2)}`)

export default function LegendAnalysis({ slug, onBack, onBackToList }) {
  const { data, loading, error } = useLegendCards()

  const legend = useMemo(
    () => (data?.legends || []).find((l) => l.legendSlug === slug) || null,
    [data, slug]
  )

  const sections = useMemo(() => {
    if (!legend) return []
    const byType = new Map()
    for (const card of legend.cards) {
      if (card.type === 'legend') continue // the legend itself isn't useful to list
      const type = TYPE_ORDER.includes(card.type) ? card.type : 'other'
      if (!byType.has(type)) byType.set(type, [])
      byType.get(type).push(card)
    }
    return TYPE_ORDER.filter((t) => byType.has(t)).map((t) => ({
      type: t,
      label: TYPE_LABELS[t] || t,
      cards: byType.get(t),
    }))
  }, [legend])

  if (loading) return <div className="app-status">Loading card analysis…</div>
  if (error) return <div className="app-status app-status--error">{error}</div>

  if (!legend) {
    return (
      <div className="legend-analysis">
        <button type="button" className="legal-back" onClick={onBackToList}>
          ← All legends
        </button>
        <div className="app-status">
          No card analysis found for this legend yet. It is generated by the daily data update.
        </div>
      </div>
    )
  }

  return (
    <section className="legend-analysis">
      <button type="button" className="legal-back" onClick={onBackToList}>
        ← All legends
      </button>

      <header className="legend-analysis-head">
        {legend.legendTileUrl && (
          <span
            className="legend-analysis-tile"
            style={{ backgroundImage: `url(${legend.legendTileUrl})` }}
            aria-hidden="true"
          />
        )}
        <div>
          <h2 className="legend-analysis-name">{legend.legendName}</h2>
          <p className="legend-analysis-meta">
            Based on {legend.decksSampled} sampled deck{legend.decksSampled !== 1 ? 's' : ''} of{' '}
            {legend.totalDecks} tracked. Inclusion = share of sampled decks running the card.
          </p>
        </div>
      </header>

      {sections.map((section) => (
        <div key={section.type} className="legend-section">
          <h3 className="legend-section-title">
            {section.label} <span className="legend-section-count">{section.cards.length}</span>
          </h3>
          <ul className="card-rows">
            {section.cards.map((card) => (
              <li key={card.cardUrl || card.name} className="card-row">
                {card.imageSrc ? (
                  <img className="card-row-img" src={card.imageSrc} alt="" loading="lazy" />
                ) : (
                  <span className="card-row-img card-row-img--empty" aria-hidden="true" />
                )}
                <div className="card-row-main">
                  <div className="card-row-top">
                    {card.cardUrl ? (
                      <a
                        className="card-row-name"
                        href={`${BASE}${card.cardUrl}`}
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        {card.name}
                      </a>
                    ) : (
                      <span className="card-row-name">{card.name}</span>
                    )}
                    {section.type !== 'battlefields' && (
                      <span className="card-row-copies">{card.avgCopies}× avg</span>
                    )}
                  </div>
                  <div className="card-row-bar">
                    <span
                      className="card-row-bar-fill"
                      style={{ width: `${Math.max(3, card.inclusionRate * 100)}%` }}
                    />
                  </div>
                </div>
                <div className="card-row-stats">
                  {section.type !== 'runes' && (
                    <span className="card-row-incl">{fmtPct(card.inclusionRate)}</span>
                  )}
                  <span className="card-row-price">{fmtMoney(card.price)}</span>
                </div>
              </li>
            ))}
          </ul>
        </div>
      ))}
    </section>
  )
}
